name: dpll_tests
on: [ push,pull_request ]


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make 
          cd ..
        env:
          CI: true

      - name: Unit_Tests
        run: |
          cd build
          make test
        env:
          CI: true
      - name: Verify
        run: |
          cd tests
          sudo apt install picosat
          python3 ./verify.py
        env:
          CI: true